README.md

This PR setup Netlify and also adds Netlify badge to the repo
Production Url: https://hermes-ah.netlify.com
Develop Url: https://develop--ah.netlify.com
Pull Request Url: https://deploy-preview-[number]--hermes-ah.netlify.com
N/A
N/A
[#165675401](https://www.pivotaltracker.com/story/show/165675401)
N/A
N/A

#165675401 Setup Netlify

---

package-lock.json
package.json
webpack.config.js

- add sass loader
- css loader
N/A
N/A
N/A
[164797972](https://www.pivotaltracker.com/n/projects/2318856/stories/164797972)
N/A
N/A

#164797972 Setup sass

---

.travis.yml
README.md
package-lock.json

This PR sets up  TravisCi to run tests
N/A
[#164797970](https://www.pivotaltracker.com/story/show/164797970)
N/A
N/A

#164797970 Setup TravisCi to run tests

---

package.json
src/actions/auth.actions.js
src/components/containers/login.container.js
src/components/presentations/Login/Login.jsx
src/constants/auth.constants.js
src/constants/loading.constants.js
src/reducers/auth.reducer.js
src/reducers/index.js
src/reducers/loading.reducer.js
src/selector/selector.js

currently we have to manually set our loader to false from each of our separate reducers. But with this new implementation, we now have our loader controller happening in a single place
[165853702](https://www.pivotaltracker.com/story/show/165853702)

#165853702 Implement redux loader

---

src/components/presentations/Bookmarked/Article/Article.jsx
src/components/presentations/Bookmarked/Article/article.scss
src/components/presentations/Bookmarked/Bookmaked.jsx
src/components/presentations/Bookmarked/bookmarked.scss
src/components/presentations/ProfileTab/ProfileTab.jsx
src/components/presentations/Profilepage/ProfilePage.jsx
src/components/presentations/Profilepage/__test__/Profilepage.test.jsx
src/components/presentations/Profilepage/profilepage.scss

This adds a `CSS` style to the `<Bookmarked />` component and also implement bookmark article count, placing the total number of bookmark on the `bookmark badge`.
[165879188](https://www.pivotaltracker.com/n/projects/2318856/stories/165879188)
N/A

#165879188 Add CSS Style Bookmark Component

---

src/App.jsx
src/actions/auth.actions.js
src/components/containers/homepage.container.js
src/components/presentations/Homepage/Homepage.jsx
src/components/presentations/Login/__test__/Login.test.js
src/components/presentations/Login/__test__/Login.test.jsx
src/components/presentations/Signup/Signup.jsx

Currently, users can't verify their account on Authors Haven. This PR implement email verification process.
N/A
[Finishes 164797975](https://www.pivotaltracker.com/n/projects/164797975)
N/A

#164797975 Implement Email Verification

---

public/index.html
src/App.jsx

Currently, when a user redirects to a valid link but include a '/' in front of it, the user won't be able to see that page. This PR fixes the bug in routing
[#165893050](https://www.pivotaltracker.com/story/show/165893050)
N/A
N/A

#165893050 Fix Routing Bug

---

package.json
src/components/containers/nav.container.js
src/components/presentations/Profilepage/ImagePic.jsx
src/components/shared/NavBar/AuthNavBar.jsx
src/components/shared/NavBar/NavBar.jsx
src/components/shared/NavBar/NavBarDropdown.jsx
src/components/shared/NavBar/__test__/NavBar.test.jsx
src/components/shared/NavBar/navbar.scss

This PR includes the navbar dropdown when the user is logged in
- create navbar component
[#164797979](url)

#164797979 Navbar dropdown

---

src/components/presentations/Bookmarked/Article/__test__/Article.test.jsx
src/components/presentations/Bookmarked/Article/__test__/__snapshots__/Article.test.jsx.snap
src/components/presentations/Bookmarked/__test__/Bookmarked.test.jsx
src/components/presentations/Bookmarked/__test__/__snapshots__/Bookmarked.test.jsx.snap
src/components/presentations/ProfileTab/__test__/ProfileTab.test.jsx
src/components/presentations/Profilepage/__test__/Profilepage.test.jsx

Currently, some components that interact with the `<Bookmarked />` do not reflect its presence on their respective tests and also the component does not have a test suite. This `PR` implements all these.
[165879188](https://www.pivotaltracker.com/n/projects/2318856/stories/165879188)
N/A
N/A

#165879188 Bookmark Test

---

src/App.jsx
src/actions/auth.actions.js
src/components/presentations/Logout/Logout.jsx
src/components/shared/NavBar/NavBarDropdown.jsx
src/utils/authService.js

Currently, users cannot log out of the app. This PR implement the logout functionality
[#165906261](https://www.pivotaltracker.com/story/show/165906261)
N/A
N/A

#165906261 Implement Logout Feature

---

src/components/presentations/Profilepage/__test__/Profilepage.test.jsx
src/components/shared/NavBar/NavBarDropdown.jsx

This PR updates the bug on the navbar. 
N/A
N/A
N/A
N/A
N/A

Bug: update navbar bug

---

src/actions/auth.actions.js
src/actions/resetPassword.actions.js
src/components/presentations/Homepage/Homepage.jsx
src/components/presentations/Profilepage/ProfilePage.jsx

Currently, our application auto redirects user during the password reset process. This PR implements a nice user experience on password reset.
Non-breaking change
N/A
N/A
[](url)
N/A

Bug: fix reset password redirect bug

---

src/components/presentations/UserFollwing/__test__/Followee.actions.test.js
src/components/presentations/UserFollwing/__test__/Followee.reducer.test.js
src/components/presentations/UserFollwing/__test__/Following.actions.test.js
src/components/presentations/UserFollwing/__test__/Following.reducer.test.js
src/components/presentations/UserFollwing/__test__/__snapshots__/userFollowing.test.jsx.snap
src/components/presentations/UserFollwing/__test__/userFollowing.test.jsx

Currently our components for this feature is not tested. This PR lads test cases for all the components
[#164797987](https://www.pivotaltracker.com/story/show/164797987)
N/A

#164797987 write tests for components

---

src/components/presentations/HeroView/hero-view.scss
src/components/shared/Form/form.scss
src/components/shared/NavBar/navbar.scss

During our last demo. our PO had some feedback on the hover effect we used on our buttons. this PR implements the recommended.
N/A
N/A

Implement feedback on homepage

---

package.json
src/App.jsx
src/components/presentations/AdminPage/AdminPage.jsx
src/components/presentations/AdminTab/AdminTab.jsx
src/components/presentations/AdminTab/AdminTabButton.jsx
src/components/presentations/AdminTab/admintab.scss
src/components/shared/NavBar/NavBarDropdown.jsx

This PR creates the skeleton of an admin profile page. 
- [] Unit testing
- [] End to end
- create an admin profile page
[#165904619](https://www.pivotaltracker.com/story/show/165904619)
N/A

#165904619 implement admin profile page

---

src/components/containers/userprofile.container.js
src/components/presentations/UserProfile/SuggestedArticleCard.jsx
src/components/presentations/UserProfile/UserProfile.jsx
src/components/presentations/UserProfile/__tests__/Userprofile.test.jsx
src/components/presentations/UserProfile/userprofile.scss

This Pr implements the feature where a user gets to see suggested articles
- implement user can see suggested article
- Update test cases
[#164797979](url)
N/A

#164797979 Get suggested articles

---

src/components/presentations/PasswordReset/ResetPassword.jsx
src/components/shared/Form/form.scss

This PR handles responsiveness for auth pages
[164797975](https://www.pivotaltracker.com/story/show/164797975)

#164797975 Auth pages responsiveness

---

src/components/presentations/UserFollwing/FollowCard/follow-card.scss
src/components/presentations/UserFollwing/Followee/Followee.jsx
src/components/presentations/UserFollwing/Following/Following.jsx

This is a PR that implements some feedback received from our product owner 
[#164797979](https://www.pivotaltracker.com/n/projects/2318856/stories/164797979)

#164797979 Implement feedback from PO

---

package-lock.json
src/components/presentations/ProfileTab/ProfileTabButton.jsx
src/components/presentations/ProfileTab/profiletab.scss

The shape of the badges are oblong, this `PR` restyle and make it round.
[164797979](https://www.pivotaltracker.com/n/projects/2318856/stories/164797979)
N/A

#164797979 Change Shape of the Profile Badges

---

src/actions/profile.action.js
src/components/containers/userprofile.container.js
src/components/presentations/Profilepage/ImagePic.jsx
src/components/presentations/Profilepage/ProfilePage.jsx
src/components/presentations/Profilepage/__test__/Profilepage.actions.test.js
src/components/presentations/Profilepage/__test__/Profilepage.reducer.test.js
src/components/presentations/Profilepage/__test__/Profilepage.test.jsx
src/components/presentations/Profilepage/profilepage.scss
src/components/presentations/UserProfile/ProfileCard.jsx
src/components/presentations/UserProfile/UserProfile.jsx
src/components/presentations/UserProfile/__tests__/Userprofile.test.jsx
src/components/presentations/UserProfile/__tests__/Userprofilecards.test.jsx
src/components/presentations/UserProfile/userprofile.scss

This PR implements user can edit profile
[#164797979](url)
N/A
N/A

#164797979 User can edit profile

---

src/App.jsx
src/actions/auth.actions.js
src/components/presentations/Login/Login.jsx
src/components/shared/ProtectedRoute/ProtectedRoute.jsx

Currently, if an unauthorized user tries to access a protected route he/she will be able to access the page, the PR redirect an unauthorized user to the login page when they tried to access a protected route
[#165964809](https://www.pivotaltracker.com/story/show/165964809)
N/A
N/A

#165964809 Fix Protected Route Bug

---

src/utils/authService.js
src/utils/httpService.js

This PR refactor the Axios configuration
N/A
N/A
N/A

Chore: Refactor Axios Configuration

---

package-lock.json
package.json
public/index.html
src/App.jsx
src/App.scss
src/assets/stylesheets/index.scss
src/components/presentations/CookieBanner/CookieBanner.jsx
src/components/presentations/Homepage/Homepage.jsx
src/components/presentations/Homepage/homepage.scss
src/components/presentations/Notfound/notfound.scss
src/components/presentations/Profilepage/ProfilePage.jsx
src/components/presentations/UserHomepage/user-homepage.scss

This PR implements cookie banner consent so that users are aware of some actions on their computer
[165968512](https://www.pivotaltracker.com/story/show/165968512)

#165968512 Cookie banner consent

---

package-lock.json
src/assets/stylesheets/index.scss
src/components/presentations/ArticleCard/article-card.scss

Currently, the scrollbar is always visible on the authenticated and unauthenticated homepage and doesn't go hidden. This P.R adds the ability for the scrollbar to go invisible, but become visible when a user hovers over the articles.
[165980229]](https://www.pivotaltracker.com/n/projects/2318856)
N/A

#165980229 update scroll bar

---

src/App.jsx
src/actions/auth.actions.js
src/actions/profile.action.js
src/components/presentations/Login/__test__/Login.test.js
src/components/presentations/Signup/__test__/signup.action.test.js
src/components/presentations/SocialLogin/SocialLogin.jsx
src/components/shared/Form/Form.jsx
src/components/shared/Form/__test__/__snapshots__/Form.test.jsx.snap
src/components/shared/Form/form.scss
src/components/shared/NavBar/NavBarDropdown.jsx

This PR implements social login for the App
N/A
[#164797978](https://www.pivotaltracker.com/story/show/164797978)
N/A

#164797978 Implement Social Login

---

src/components/presentations/ArticleCard/__test__/ArticleCard.test.jsx
src/components/presentations/Bookmarked/__test__/Bookmarked.test.jsx
src/components/presentations/ProfileTab/__test__/ProfileTab.test.jsx
src/components/presentations/Profilepage/__test__/Profilepage.test.jsx
src/components/presentations/UserFollwing/__test__/userFollowing.test.jsx
src/components/presentations/UserHomepage/__test__/UserHomepage.test.jsx
src/components/presentations/UserProfile/__tests__/Userprofile.test.jsx
src/utils/testMocks.js

This PR implements creating a file mock to store data that will be tested
N/A
N/A
N/A
N/A

Chore: Update test mock

---

package-lock.json
public/index.html
src/actions/profile.action.js
src/actions/reported.actions.js
src/components/presentations/Profilepage/ProfilePage.jsx
src/components/presentations/Profilepage/__test__/Profilepage.reducer.test.js
src/components/presentations/Profilepage/__test__/Profilepage.test.jsx
src/components/presentations/UserProfile/UserProfile.jsx
src/components/shared/NavBar/NavBarDropdown.jsx
src/components/shared/NavBar/__test__/NavBar.test.jsx
src/reducers/profile.reducers.js

Currently, the implementation of the user profile is not making full use of the power of Redux. This PR removes the unnecessary logic `componentDidUpdate` and makes use of the store directly.
- Refactor profile logic
N/A
N/A
N/A

Chore: Refactor profile logic

---

src/components/presentations/ArticleCard/article-card.scss
src/components/presentations/HeaderCard/headercard.scss
src/components/presentations/Homepage/homepage.scss
src/components/presentations/UserArticles/author-articles.scss
src/components/presentations/UserHomepage/user-homepage.scss
src/components/presentations/UserProfile/userprofile.scss

This PR fixes feedback on the user profile page
[](url)
N/A

Chore: Fix user profile page feedback

---

src/components/presentations/AdminPage/AdminPage.jsx
src/components/presentations/AdminTab/admintab.scss
src/components/presentations/ReviewedArticles/ReviewedArticles.jsx
src/components/presentations/ReviewedArticles/ReviewedArticlesCard.jsx
src/components/presentations/ReviewedArticles/reviewed-articles-card.scss
src/components/presentations/ReviewerRequests/Requests/Requests.jsx
src/components/presentations/ReviewerRequests/ReviewersCard/Reviewers-card.jsx
src/utils/dummyData.js

Currently admin can access articles that have been reviewed however the reviewed articles data are dummy data
N/A
N/A
[165904619](https://www.pivotaltracker.com/story/show/165904619)

#165904619: Reviewed articles

---

src/components/containers/admin.container.js
src/components/presentations/AdminPage/AdminPage.jsx
src/components/presentations/AdminPage/ReportedArticles.jsx
src/components/presentations/AdminTab/AdminTab.jsx
src/components/presentations/ReviewedArticles/reviewed-articles-card.scss
src/components/presentations/ReviewerRequests/ReviewersCard/reviewers-card.scss

This PR enables admin to view reported articles
[165904619](https://www.pivotaltracker.com/story/show/165904619)

#165904619 Reported articles(Admin)

---

package-lock.json
src/components/presentations/Profilepage/__test__/Profilepage.actions.test.js
src/components/presentations/Profilepage/__test__/Profilepage.reducer.test.js
src/components/presentations/UserProfile/ProfileCard.jsx
src/components/presentations/UserProfile/__tests__/Userprofile.test.jsx
src/components/presentations/UserProfile/__tests__/Userprofilecards.test.jsx

This PR updates test cases and the profile edit logic
N/A
N/A
N/A

Chore: update test cases and profile edit logic

---

src/components/presentations/NewArticle/NewArticle.jsx
src/components/presentations/NewArticle/NewArticleForm/keywords.jsx
src/components/presentations/NewArticle/NewArticleForm/new-article.scss

Currently, the padding on the abstract and editor are not the same with the title. This P.R adds the ability for them to be equal. 
[164797980](https://www.pivotaltracker.com/n/projects/2318856)
N/A
N/A

#164797980 implement feedback on create article 

---

src/components/presentations/UserArticles/Article/Article.jsx
src/components/presentations/UserFollowing/FollowCard/follow-card.scss

This `PR` add responsiveness to the follower and the following page
N/A
[166080755](https://www.pivotaltracker.com/story/show/166080755)
N/A
N/A

#166080755 Update Responsiveness to the Page

---

src/components/presentations/AdminPage/AdminPage.jsx
src/components/presentations/AdminPage/admin.scss

This `PR` add a minimum height to the admin page
N/A
N/A
N/A
N/A

Update Admin Page Min-height

---

src/actions/resetPassword.actions.js
src/components/presentations/PasswordReset/ResetPassword.jsx
src/components/presentations/PasswordReset/__test__/Resetpassword.test.js
src/components/presentations/PasswordReset/__test__/Resetpassword.test.jsx

This PR fixes the reset password bug
N/A
N/A

Bug: Reset Password Bug

---

src/assets/stylesheets/index.scss
src/components/presentations/ArticleCard/article-card.scss
src/components/presentations/Homepage/Homepage.jsx
src/components/presentations/PopularArticleCard/PopularArticleCard.jsx
src/components/presentations/PopularArticleCard/popular-article-card.scss
src/components/presentations/UserHomepage/UserHomepage.jsx
src/components/presentations/UserHomepage/user-homepage.scss

Previously the Popular post section keeps jumping around on page refresh whereas it is supposed to be displayed in descending order of the top 3 most liked articles. Currently it is working as expected. We also added the primary colour to the article title and category on the homepage and user homepage
[](url)
N/A

Bug: Fix homepage feedback and popular post bugs
